#민감 정보는 윈도우 시스템 환경변수에 등록
server:
  port: 8080
spring:
  application:
    name: DateManagerBackend
    #데이터베이스 연결 설정(드라이버/URL/접속 계정)
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: ${ORACLE_USERNAME}
    password: ${ORACLE_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create #이후 update로 변경
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
  data:
    web:
      pageable:
        one-indexed-parameters: true #pageable index에서 자동으로 1을 빼기위한 설정(예: ?page=3요청시 pagebale index는 2
        page-parameter: page #page 파라미터변경(기본값:page)

  #스웨거 UI URL 설정
  springdoc:
    swagger-ui:
      path: /swagger-ui.html #기본 주소인 /swagger-ui/index.html로 리다이렉트
  #게시글 페이지 사이즈 설정
  post:
    page-size: 4
  #AWS S3 버킷에 대한 IAM유저 인증관련 키 설정(키는 임의 키)
  cloud:
    aws:
      credentials:
        access-key: ${S3_ACCESS_KEY} # AWS에서 발급받은 Access Key
        secret-key: ${S3_SECRET_KEY} # AWS에서 발급받은 Secret Key
      region: ap-northeast-2 # 서울 리전 기준
      s3:
        bucket:  # 생성한 S3 버킷 이름

  #JWT 토큰 비밀키 및 만료시간 설정(키는 임의명)
  #-비밀 키(JSON WEB TOKEN 해쉬 및 서명 확인에 사용)
  #-32자 이상(256bit) 대문자와 소문자,숫자,+,=,/만 허용
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration-ms: 3600000 #엑세스 토큰 유효시간(1시간)
